name: iOS - Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: iOS build setup
        run: xcodebuild build-for-testing -scheme TestMe  -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2'

      - name: testing ... iPhone 11
        run: xcodebuild test-without-building -enableCodeCoverage YES -scheme TestMe -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2'

      - name: Coverage
        run: xcrun xccov view Logs/Test/*.xcresult --json > coverage.json
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0

