name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests
        run: xcodebuild test -enableCodeCoverage YES -scheme TestMe -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.2' 
    
      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
          with:
            ruby-version: 2.7.2
            bundler-cache: true
            
      - name: Coverage 
        run: bundle exec fastlane coverage
      # - name: Run Coverage
      #   run: xcrun xccov vierew –report –json "CodeCoverage.xcresult" > "CodeCoverage.json"
     
      # - name: Gather Coverage
      #   run: ruby ./scripts/coverage.rb