name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint
        run: swiftlint lint --quiet

      - name: Bundle install
        run: bundle install
       
      # - name: Tests
      #   run: bundle exec fastlane tests

      - name: Coverage 
        run: bundle exec fastlane coverage